lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/nf-core-admixpipe_logo_light.png
    - docs/images/nf-core-admixpipe_logo_light.png
    - docs/images/nf-core-admixpipe_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - docs/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - assets/email_template.html
    - assets/email_template.txt
    - assets/nf-core-admixpipe_logo_light.png
    - docs/images/nf-core-admixpipe_logo_light.png
    - docs/images/nf-core-admixpipe_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: Tyler K. Chafin
  description: aCaMEL NextFlow DSL2 implementation of AdmixPipe
  force: false
  is_nfcore: false
  name: admixpipe
  org: aCaMEL
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  version: 1.0dev
